- ffda-usb-wan-hotplug/Makefile
- ffda-usb-wan-hotplug/files/etc/config/usb-wan-hotplug
- ffda-usb-wan-hotplug/files/etc/hotplug.d/usb/10-usb-wan-hotplug
- ffda-usb-wan-hotplug/luasrc/usr/bin/usb-wan-hotplug
The usb-wan-hotplug package allows for USB ethernet devices (e.g.
smartphones providing USB tethering) to be used as the WAN interface.
> ffda-usb-wan-hotplug: add package

- ffda-usb-wan-hotplug/Makefile
- ffda-usb-wan-hotplug/files/etc/init.d/gluon-usbmuxd
This adds support for tethering Apple devices.
It uses usbmuxd to query the device for authorizing trust. As OpenWrt 19.07, this package also now contains an initscript for usbmuxd.
> ffda-usb-wan-hotplug: add support for tethering iOS

- .luacheckrc
- ffda-gluon-usteer/Makefile
- ffda-gluon-usteer/README.md
- ffda-gluon-usteer/check_site.lua
- ffda-gluon-usteer/files/etc/config/gluon-usteer
- ffda-gluon-usteer/luasrc/lib/gluon/upgrade/750-gluon-usteer
This package provides a Gluon-specific integration, the OpenWrt WiFi roaming & steering daemon.
This package provides a tiered configuration. It is hard to provide a configuration, which covers all possible deployment environments.
The following configuration options can be configured using the site as well as the `gluon-usteer` configuration package.
> ffda-gluon-usteer: add package

- ffda-gluon-usteer/luasrc/lib/gluon/upgrade/750-gluon-usteer
The mesh-interface were not updated to the new names currently used by Gluon.
> ffda-gluon-usteer: update mesh interface names

- ffda-gluon-usteer/luasrc/lib/gluon/upgrade/750-gluon-usteer
Limit usteer operation to SSIDs used for the client network. This
prevents distribution of information about clients of the private wlan
to adjacent nodes.
Signed-off-by: David Bauer <mail@david-bauer.net>
> ffda-gluon-usteer: limit operation to client SSIDs

- ffac-eol-ssid/Makefile
- ffac-eol-ssid/README.md
- ffac-eol-ssid/luasrc/lib/gluon/upgrade/950-eol-ssid-nagger
The Readme is probably missing here yet, but I would like to get opinions on adding these packages
related packages:
https://gitlab.karlsruhe.freifunk.net/firmware/packages/-/blob/master/ffka-eol-ssid/
https://github.com/freifunkMUC/gluon-packages/tree/main/ffmuc-eol-ssid/
> ffac-eol-wifi: add eol_wifi with configurable ssid

- ffac-change-autoupdater/LICENSE
- ffac-change-autoupdater/Makefile
- ffac-change-autoupdater/README.md
- ffac-change-autoupdater/files/lib/gluon/upgrade/505-change-autoupdater
- configurable through site, see README
- I could have multiple branches implemented as a dict of migrations, but I decided against it, as I did not need this migration and therefore could not test it thoroughly
- tested in ffac
fixes #26
> ffac-change-autoupdater: add package to switch autoupdater branch

- ffac-scheduled-sysupgrade/LICENSE
- ffac-scheduled-sysupgrade/Makefile
- ffac-scheduled-sysupgrade/README.md
- ffac-scheduled-sysupgrade/check_site.lua
- ffac-scheduled-sysupgrade/luasrc/lib/gluon/scheduled-sysupgrade/do-sysupgrade
- ffac-scheduled-sysupgrade/luasrc/lib/gluon/upgrade/950-gluon-scheduled-domain-switch
- ffac-scheduled-sysupgrade/luasrc/usr/bin/gluon-check-available
For upcoming firmware migrations in FFAC I built a package which an downloads the firmware via autoupdater -n and installs it later, so that other nodes can make sure to receive the update before the breaking install happens.
use-case: changes of the site.mk bring incompatibility with the previous firmware, autoupdater-wifi-fallback doesn't help because uplink came via mesh-on-wan (e.g. from nanopi or x86 offloader)
if only the site.conf is affected - one should use scheduled-domain-switch, if the site.mk is also affected, this package should be used for migrations
> ffac-scheduled-sysupgrade: add scheduled sysupgrade package

- ffac-autoupdater-wifi-fallback/LICENSE
- ffac-autoupdater-wifi-fallback/Makefile
- ffac-autoupdater-wifi-fallback/README.md
- ffac-autoupdater-wifi-fallback/files/etc/config/autoupdater-wifi-fallback
- ffac-autoupdater-wifi-fallback/luasrc/lib/gluon/upgrade/510-autoupdater-wifi-fallback
- ffac-autoupdater-wifi-fallback/luasrc/usr/lib/lua/autoupdater-wifi-fallback/util.lua
- ffac-autoupdater-wifi-fallback/luasrc/usr/sbin/autoupdater-wifi-fallback
- ffac-autoupdater-wifi-fallback/src/Makefile
- ffac-autoupdater-wifi-fallback/src/respondd.c
This is a draft version using `wpa-supplicant-mini` which adds around 220KB to the firmware.
This is needed for the package to be supported in versions 2022.x and greater.
Test worked fine on a o2-6431 box running v2022.1.4
> ffac-autoupdater-wifi-fallback: add fallback wifi autoupdater

- ffac-mesh-vpn-wireguard-openwrt19/Makefile
- ffac-mesh-vpn-wireguard-openwrt19/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
- ffac-mesh-vpn-wireguard-openwrt19/gluonShellDiet.sh
adding shelldiet removes comments from scripts on package install
this reduces the installed script size, as there are some devices in the old target which are very near to their limit
> [ffac-mesh-vpn-wireguard-openwrt19] add shelldiet 

- ffac-eol-ssid/Makefile
- ffac-eol-ssid/README.md
- ffac-eol-ssid/files/etc/config/eol-ssid
- ffac-eol-ssid/luasrc/lib/gluon/upgrade/950-eol-ssid-nagger
Before thie change, the eol-ssid uci subsystem had to be created manually and the uci settings did not show up for this package.
> ffac-eol-ssid: fix name of eol-ssid uci subsystem

- .github/workflows/lint.yml
Silences node12 warning.
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info:
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> ci: use action/checkout@v4

- ffac-eol-ssid/README.md
- ffac-eol-ssid/check_site.lua
- ffac-eol-ssid/luasrc/lib/gluon/upgrade/950-eol-ssid-nagger
Change "eol_wifi" to "eol_ssid", as the package is called "...-eol-ssid".
Allow toggling the "enabled" boolean per domain/site without the need to touch uci configs.
> ffac-eol-ssid: rework site configuration

- ffmuc-ipv6-ra-filter/files/lib/gluon/ffmuc-ipv6-ra-filter/ipv6-ra-filter
The "ebtables-tiny -L" is called regularly and the output is printed as log messages of micron.d causing unnecessary log spam.
> ffmuc-ipv6-ra-filter: make filter less verbose

- ffac-ssid-changer/shsrc/ssid-changer.sh
Fixing shellcheck errors:
- SC2046: quote to prevent word splitting.
- SC2061: quote so the shell won't interpret it.
> ffac-ssid-changer: add quotes to avoid interpret.

- ffac-ssid-changer/shsrc/ssid-changer.sh
Fixes shellcheck SC2045:
Iterating over ls output is fragile. Use globs.
For more information see https://github.com/koalaman/shellcheck/wiki/SC2045 and related links.
> ffac-ssid-changer: use globs instead of ls output

- ffac-ssid-changer/README.md
- ffac-ssid-changer/shsrc/ssid-changer.sh
Currently, the ffac-ssid-changer is very verbose and causes excessive logging on devices without a WiFi device (e.g. offloaders).
This change makes the logging configurable via uci.
> ffac-ssid-changer: make extra logging configurable

- ffac-eol-ssid/luasrc/lib/gluon/upgrade/950-eol-ssid-nagger
Currently, the eol-ssid only is shown if enabled is set to 1. This currently only happens if it was migrated from a previous package and the option was set there as well.
Changing this will send the eol-ssid even if the configuration is empty, i.e. for new devices.
> ffac-eol-ssid: enable ssid if uci config is unset

- ffac-mesh-vpn-wireguard-openwrt19/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
- ffac-mesh-vpn-wireguard-openwrt19/gluonShellDiet.sh
ShellCheck has no "first class support" for `busbox sh` , but instead relies on the `ash` parsing that in turn uses Debian's `dash` implementation.
So I do (correctly) specify `#!/bin/busybox sh` but then tell shellcheck to also accept dash parsing.
See https://www.shellcheck.net/wiki/SC2187 for more details.
> ffac-mesh-vpn-wireguard-owrt19: fix all shellcheck issues

- ffda-mesh-vpn-fastd-sqm/Makefile
- ffda-mesh-vpn-fastd-sqm/files/etc/config/ffda-mesh-vpn-sqm
- ffda-mesh-vpn-fastd-sqm/luasrc/lib/gluon/upgrade/510-ffda-mesh-vpn-fastd-sqm
This package allows to enable SQM instead of simple-tc on fastd mesh vpn interfaces.
SQM is only enabled if the device has a sufficient amount of system-memory, namely at least 256MB.
> ffda-mesh-vpn-fastd-sqm: add package

- ffac-mesh-vpn-wireguard-openwrt19/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
- ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
- set -e, -u and pipefail to make errors more transparent
- rework code with the new -e and -u requirements
- replace `$3ff` with `${3}ff` to be transparent that it is not `${3ff}`
- abort with a log message if mesh-vpn could not be created
> *-mesh-vpn-wireguard-vxlan: improve error handling and other fixes

- ffac-mesh-vpn-wireguard-openwrt19/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
- ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
The change improves the code in a few areas:
- remove arguments, the function interface_linklocal takes no arguments
- use variable to avoid calling it 3 times
- use variable to avoid masking return values (SC2312) https://github.com/koalaman/shellcheck/wiki/SC2312
> *-mesh-vpn-wireguard: improve linklocal calls

- .github/workflows/shellcheck.yml
A proposal to add some shell linting as there are quite some shell scripts in this repository.
> ci: add shell linting workflow

- README.md
The link doesn't exist anymore.
What was once there can be seen via archive.org:
https://web.archive.org/web/20191116085527/https://spdx.org/ids-how
The new link offers the same info.
> readme: fix link to SPDX FAQ

- ffgraz-ddhcpd-batman-adv/files/usr/sbin/ddhcpd-gateway-update
This includes a bit of restructuring the flow as the A && B || C can run C if either A or B fails. This seemed unintentional.
> ffgraz-ddhcpd-batman-adv: fix shellcheck issues

- README.md
I update the readme and clarified some information on how to contribute and which things have to be respected.
This makes sure that
* contributions have the same pattern
* commits relate to a given package
* makes sure that a license is given
* introduces the community-independant ff- slug
* clarifies some guidelines of the community-packages workflow
fixes #2
> readme: update readme, clarify some guidelines and improve example

- ff-mesh-vpn-tunneldigger/Makefile
- ff-mesh-vpn-tunneldigger/README.md
- ff-mesh-vpn-tunneldigger/check_site.lua
- ff-mesh-vpn-tunneldigger/files/lib/gluon/reload.d/310-tunneldigger-stop
- ff-mesh-vpn-tunneldigger/files/lib/gluon/reload.d/790-tunneldigger-start
- ff-mesh-vpn-tunneldigger/files/usr/lib/micron.d/tunneldigger-watchdog
- ff-mesh-vpn-tunneldigger/luasrc/lib/gluon/upgrade/400-mesh-vpn-tunneldigger
- ff-mesh-vpn-tunneldigger/luasrc/usr/bin/tunneldigger-watchdog
- ff-mesh-vpn-tunneldigger/luasrc/usr/lib/lua/gluon/mesh-vpn/provider/tunneldigger.lua
This is a dump of the former core package gluon-mesh-vpn-tunneldigger:
https://github.com/freifunk-gluon/gluon/tree/c2dc338abfbebb34dcf62124dc09be85fa88f8ef/package/gluon-mesh-vpn-tunneldigger
Only neccesary changes have been made.
I haven't tested this.
> ff-mesh-vpn-tunneldigger: init

- ffda-gluon-ssh-manager/Makefile
- ffda-gluon-ssh-manager/README.md
- ffda-gluon-ssh-manager/files/etc/config/ffda-ssh-manager
- ffda-gluon-ssh-manager/luasrc/lib/gluon/upgrade/860-ffda-ssh-manager
This is a utility package which allows communities to add their own key-groups using their site-configuration.
Configuration is done using UCI. The following config-keys exist:
- `ffda-ssh-manager.settings.enabled`
- Default: 0
- Type: boolean
- Enables gluon-ssh-manager.
- `ffda-ssh-manager.settings.group`
- Default: nil
- Type: list
- Selects the groups to roll out on a node.
ssh-manager will add the group-keys to the end of dropbears `authorized_keys` file.
This block is identified by a block-start comment. Each key is appended with a comment, associating
these keys with ssh-manager.
Keys with this trailing comment are removed when they are removed from the key-group or ssh-manager becomes
disabled.
Defaults can be defined in the `site.conf`. These will apply to nodes which are …
> ffda-gluon-ssh-manager: add package

- ffda-ssh-manager/README.md
The setting is called groups not group:
https://github.com/freifunk-gluon/community-packages/blob/1e51133bb64a1f0faddeabded786100e7f37b260/ffda-ssh-manager/luasrc/lib/gluon/upgrade/860-ffda-ssh-manager#L13
> ffda-ssh-manager: readme: fix groups settings reference

- ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
This fixes the context problem for the ntp server check.
> ffmuc-mesh-vpn-wireguard-vxlan: Fix wrong context for ntp-server update

- ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
This fixes and improves IPv6 matching
- do not strip trailing "::", for IPs like `2003:a:87f:c37c::`
- match IPs starting with ::, like `::1`
- match IPs not starting with a digit, like `fd62:f45c:4d09:180:22b3:ff::`
- match IPs containing a zone identifier ("%"), like `fe80::abcd%enp5s0`
> ffmuc-mesh-vpn-wireguard-vxlan: fix IPv6 regex

- ffgraz-config-mode-theme-funkfeuer/README.md
- ffgraz-config-mode-theme-funkfeuer/sass/gluon.scss
Fix some typos in package `ffgraz-config-mode-theme-funkfeuer`
> ffgraz-config-mode-theme-funkfeuer: fix typos

- ffgraz-config-mode-at-runtime/Makefile
There seems to be a misspelling in the Makefile of the community package `ffgraz-config-mode-at-runtime`.
> ffgraz-config-mode-at-runtime: fix depends on ffgraz-web-model

- ffmuc-mesh-vpn-wireguard-vxlan/luasrc/lib/gluon/upgrade/400-mesh-vpn-wireguard
It is not necessary to do a gluon save
> ffmuc-mesh-vpn-wireguard-vxlan: delete gluon save

- ffmuc-mesh-vpn-wireguard-vxlan/README.md
- ffmuc-mesh-vpn-wireguard-vxlan/check_site.lua
- ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
- ffmuc-mesh-vpn-wireguard-vxlan/luasrc/lib/gluon/upgrade/400-mesh-vpn-wireguard
Include:
- fixed documentation
- site validation
- wireguard key validation
- removing code nesting (best review without whitespaces)
> ffmuc-mesh-vpn-wireguard-vxlan: several improvements

- ffda-ssh-manager/luasrc/lib/gluon/upgrade/860-ffda-ssh-manager
The docs as well as the code suggest the intention to call the config section defaults.
> ffda-ssh-manager: read defaults from defaults and not default

- ffmuc-mesh-vpn-wireguard-vxlan/Makefile
- ffmuc-mesh-vpn-wireguard-vxlan/README.md
- ffmuc-mesh-vpn-wireguard-vxlan/check_site.lua
- ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
- ffmuc-mesh-vpn-wireguard-vxlan/luasrc/lib/gluon/gluon-mesh-wireguard-vxlan/parse-wgkex-response.lua
- ffmuc-mesh-vpn-wireguard-vxlan/luasrc/lib/gluon/upgrade/400-mesh-vpn-wireguard
This enables loadbalancing to actually use the supernodes to the best extend.
> ffmuc-mesh-vpn-wireguard: enable loadbalancing

- ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
awk's srand() uses only second-precision for its initial time-based seed. That leads to many routers getting the same random number.
Replacing with busybox' hexdump and /dev/urandom that provides much better random numbers.
Found in: https://github.com/freifunk-gluon/community-packages/pull/100#discussion_r1539144319
> ffmuc-mesh-vpn-wireguard: use urandom instead awk

- ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
Older versions of nslookup use a different format
> ffmuc-mesh-vpn-wireguard: fix for older nslookup 

- ffda-node-whisperer/Makefile
- ffda-node-whisperer/README.md
- ffda-node-whisperer/check_site.lua
- ffda-node-whisperer/files/node-whisperer.upgrade.lua
This program encodes information about the status of a Gluon Node into the beacons of the wireless client networks.
This information can be decoded and sent to a community using a companion app called [NodeMonitor](https://github.com/blocktrron/NodeMonitor).
> ffda-node-whisperer: add package

- ffac-ssid-changer/shsrc/ssid-changer.sh
not yet fully tested, but this should include hotfixes to solve:
use correct ONLINE_SSID_OWE to set offline state for OWE as well
this still does not work with transition mode
fixes #113 
until a fix based on https://github.com/freifunk-gluon/gluon/pull/3223 is available
use ubus call hostapd reload instead of broken HUP
fixes #93 
don't rely on hostapd radio name starting with phy
some devices have a radio named wl0 and wl1 instead in openwrt 23.05
This is a workaround, until a better fix using lua is available
fixes #39
until a better version of the ssid-changer will be available
> ffac-ssid-changer: switch to ubus call to reload hostapd and fix OWE offline ssid

- ffac-ssid-changer/shsrc/ssid-changer.sh
Private-WLAN uses br-wan instead of br-client.
Also improves usage of the network filtering, to ignore files like `hostapd-wan0.psk` or `hostapd-wan0.vlan` even though they are empty.
closes #82
> ffac-ssid-changer: ignore config if private-wlan is enabled

- ffac-ssid-changer/shsrc/ssid-changer.sh
This silences output, otherwise, micron.d logs `bridge=br-client` on each run
> ffac-ssid-changer: silence grep command

- ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
- Move code Up for early exiting
- remove unnessery code
- aline v1 code with v2 code (same order)
- remove/add some spaces
- add Info About exiting to loggers (if the scritps exist afterwards)
- move echo to logger (or should it be a echo?)
> ffmuc-mesh-vpn-wireguard: Cleanup Code

- ffmuc-custom-banner/Makefile
- ffmuc-custom-banner/README.md
- ffmuc-custom-banner/files/etc/banner.gluon
- ffmuc-custom-banner/files/etc/config/custom-banner
- ffmuc-custom-banner/luasrc/lib/gluon/upgrade/520-custom-banner
Before:
```
BusyBox v1.35.0 (2023-10-02 15:01:05 UTC) built-in shell (ash)
_______                     ________        __
|       |.-----.-----.-----.|  |  |  |.----.|  |_
|   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
|_______||   __|_____|__|__||________||__|  |____|
|__| W I R E L E S S   F R E E D O M
-----------------------------------------------------
OpenWrt 22.03-SNAPSHOT, r20278+15-a08553b3b3
-----------------------------------------------------
```
After
```
BusyBox v1.35.0 (2023-10-02 15:01:05 UTC) built-in shell (ash)
________
/ ____/ /_  ______  ____
/ / __/ / / / / __ \/ __ \
/ /_/ / / /_/ / /_/ / / / /
\____/_/\__,_/\____/_/ /_/
---------------------------------------
Community: Freifunk München v2024.4.2
Domain:    Freifunk München - Ost
Model:     Extreme Networks …
```
> ffmuc-custom-banner: add new package

- ffac-ssid-changer/shsrc/ssid-changer.sh
before, the ssid-changer did stop once a radio without br-client was found
this is fixed by switching the program flow from `break` to `continue` which was introduced under wrong assumptions in #116
> ffac-ssid-changer: control flow should continue for other interfaces

- ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
- add logging logging in case nslookup failed and
- unify the two nslookup implementations with subtle differences. Improves the error handling for nslookup
- one nslookup grep was missing the `[0-9]*`, so this should have not worked on legacy devices
- one nslookup was missing pipefail, so it hid errors during nslookup and failed only somewhere later 
- calls to `resolve_host()` were ignoring the fact that multiple hosts can be returned from nslookup. fixed with a `| head -n 1`
- enable pipefail: with the above improvementsfixes, pipefail works again
> ffmuc-mesh-vpn-wireguard: improve nslookup calls

- ffda-node-whisperer/README.md
I guess the url to the NodeMonitor repository should be updated.
@blocktrron could you please verify if the new url is correct?
> ffda-node-whisperer: update url to NodeMonitor

- ffda-usb-wan-hotplug/files/etc/hotplug.d/usb/10-usb-wan-hotplug
it should be up to the user to disable this if mesh on wan is enabled. I think it should not be harmful to have this enabled, while it of course is not very useful to have Mesh-on-WAN enabled when using the usb-wan-hotplug functionality
Currently, this package does not work with gluon version which switched to the role API
https://gluon.readthedocs.io/en/v2021.1.1/features/roles.html
closes #126
> ffda-usb-wan-hotplug: remove old mesh_wan check

- ffda-ssh-manager/README.md
- ffda-ssh-manager/luasrc/lib/gluon/upgrade/860-ffda-ssh-manager
The word `seperator` is a very common misspelling of the word `separator`.
This pull request renames a variable and a function to use the correct spelling.
> ffda-ssh-manager: rename separator variable and function

- ffac-mt7915-hotfix/LICENSE
- ffac-mt7915-hotfix/Makefile
- ffac-mt7915-hotfix/README.md
- ffac-mt7915-hotfix/files/lib/gluon/mt7915/reboot-on-error.sh
- ffac-mt7915-hotfix/files/usr/lib/micron.d/mt7915-hotfix
This package reboots the device if the mt7915-firmware hangs on ramips-mt7621 and mediatek-filogic.
It's meant as a hotfix for the mcu timeout issue: https://github.com/freifunk-gluon/gluon/issues/3154
which occurs on all devices with an mt7915 wifi driver
> ffac-mt7915-hotfix: initial package version

- ffda-wireless-rate-limiter/Makefile
- ffda-wireless-rate-limiter/README.md
- ffda-wireless-rate-limiter/files/wireless-rate-limiter.upgrade.lua
This adds a package which can be used to shape traffic on the wireless interfaces interface-wide or per-client.
> ffda-wireless-rate-limiter: add package

- ffbs-collect-debug-info/Makefile
- ffbs-collect-debug-info/src/collect-debug-info
collect-debug-info can be used by end users to dump various informations from a running device. These can be sent to the developers to debug or provice support for node specific problems without gaining access to the target device.
> Add package ffbs-collect-debug-info

- ffbs-debugbathosts/Makefile
- ffbs-debugbathosts/README.md
- ffbs-debugbathosts/files/etc/bat-hosts
- ffbs-debugbathosts/files/usr/sbin/update-bat-hosts
This package provides `/etc/bat-hosts`.
his file can be used to map mac-addresses to names in `batctl`.
This file is empty by default and mainly serves as a reminder on how this can be used on the devices itself.
> Add ffbs-debugbathosts

- ffac-mt7915-hotfix/files/lib/gluon/mt7915/reboot-on-error.sh
This occurs on devices without an mt76 phy
> ffac-mt7915e-hotfix: silence stderr from ls command in cron

- ffmuc-mesh-vpn-wireguard-vxlan/shsrc/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
ffmuc-mesh-vpn-wireguard: move code together
> ffmuc-mesh-vpn-wireguard: move code together

- ffac-autoupdater-wifi-fallback/LICENSE
- ffac-autoupdater-wifi-fallback/Makefile
- ffac-autoupdater-wifi-fallback/luasrc/lib/gluon/upgrade/510-autoupdater-wifi-fallback
- ffac-autoupdater-wifi-fallback/luasrc/usr/sbin/autoupdater-wifi-fallback
This finally fixes the additional wpa-supplicant-mini requirement for the ffac-autoupdater-wifi-fallback (see issue https://github.com/freifunk-gluon/community-packages/pull/33#issuecomment-1876069806 for more information).
As the functionality is quite handy to have it on all devices, it should not be bloated.
The package does now works again with gluon releases v2022.x and v2023.x (and should still work on older releases) without additional wpasupplicant packages.
It uses `ubus call add_dynamic`  to add a network at runtime and then attach it to a network device.
> ffac-autoupdater-wifi-fallback: remove requirement of wpa-supplicant

- ffbs-wireguard-respondd/Makefile
- ffbs-wireguard-respondd/README.md
- ffbs-wireguard-respondd/src/Makefile
- ffbs-wireguard-respondd/src/respondd.c
- ffbs-wireguard-respondd/src/wireguard.c
- ffbs-wireguard-respondd/src/wireguard.h
This adds ffbs-wireguard-respondd.
This package provides statistics of WireGuard interfaces via respondd.
Previously this package has been managed in
https://gitli.stratum0.org/ffbs/ffbs-packages under the name `gluon-ffbsnext-wireguard`.
Last commit-id: c865bd1e81c401bbc47a1b55c0ee4b4c4893a3ec
> Add ffbs-wireguard-respondd

- ffac-wg-registration/files/lib/gluon/wg-registration/registration.sh
- ffmuc-mesh-vpn-wireguard-vxlan/shsrc/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
We therefore pipe the output to /dev/null so that the below error message does not appear in `logread` output.
The Error message is:
`SSL error: NET - Sending information through the socket failed`
The returncode behavior stays the same otherwise.
> wireguard-registration: on openwrt24.10 the https check prints to stderr

- ffac-ssid-changer/shsrc/ssid-changer.sh
This was done in #117 but the case when going offline was missing.
This is finally fixed with this PR for the "old ssid-changer", until the new one from #138 is ready
> ffac-ssid-changer: silence grep if going offline

- ffbs-parker-nextnode/Makefile
- ffbs-parker-nextnode/README.md
- ffbs-parker-nextnode/files/lib/gluon/ebtables/399-localnode
Thia adds ffbs-parker-nextnode - a package of the *parker*-flavor of Gluon.
This package provides `ebtables`-rules that redirect traffic to the
`localnode` IPs on the node itself.
This is needed in networks where the `localnode` addresses are outside the client network - for example when 
using with `parker`.
In Freifunk Braunschweig, for example, the `localnode` address is `2001:bf7:382:0::1`.
But the IP addresses of routers and clients are in `2001:bf7:381::`.
With this rule traffic to the `localnode` address is always forwarded to the router.
(The service on the router should redirect the client to one of routers public addresses - otherwise the TCP connection
would break when the client roams to another node with the same redirect.)
Previously this package has been managed in …
> Add ffbs-parker-nextnode

- ffbs-mesh-vpn-parker/files/etc/init.d/nodeconfig
We actually want to split these arguments to procd_set_param command. Otherwise procd reports a crash loop.
> ffbs-mesh-vpn-parker: fix shell word splitting

- ffbs-mesh-vpn-parker/files/usr/lib/autoupdater/upgrade.d/85parker
Removing all wireguard interfaces on autoupdate is important: This way we reduce the memory footprint during update.
Parker (in Braunschweig) has moved from using only three pre-defined interfaces to using multiple interfaces.
Others communities will likely do the same.
With this change we remove all `wg_*` interfaces.
> ffbs-mesh-vpn-parker: Remove all wireguard interfaces on autoupdate

- .github/workflows/lint.yml
- .shellcheckrc
Syncs/adds the CI linting changes that were recently added to gluon-packages: https://github.com/freifunk-gluon/packages/pull/276
The consensus during the last Gluon meetup was that the gluon-community repository shouldn't have more strict linting than the main repository.
> ci: sync linting to the version in gluon-packages

- ffbs-mesh-vpn-parker/Makefile
- ffbs-mesh-vpn-parker/files/usr/sbin/nodeconfig.sh
- ffbs-mesh-vpn-parker/files/usr/sbin/noderoute.sh
- ffbs-mesh-vpn-parker/luasrc/usr/lib/lua/gluon/mesh-vpn/provider/parker.lua
- ffbs-mesh-vpn-parker/luasrc/usr/share/lua/nodeconfig.lua
- ffbs-mesh-vpn-parker/luasrc/usr/share/lua/util.lua
Until now parker did not implement traffic shaping according to what the user defined in config mode.
With this change we implement `simple-tc` for parker. If the user now chooses to limit the bandwidth we use the standard gluon way limit the bandwidth for each tunnel individually.
We also communicate the traffic limits to the config service. This way the coordinators could also implement traffic shaping for ingress (infrastructure to router) on the infrastructure-side instead of the router in the future.
TODO:
> ffbs-mesh-vpn-parker: Implement traffic control

- ffbs-mesh-vpn-parker/files/usr/sbin/nodeconfig.sh
The `nodeconfig` and `noderoute` services both set a flag once they did their first successful run. This way other tools can now if these services completed successfully.
With this change `nodeconfig` also considers a deactivated VPN as a successful run.
Fixes https://github.com/ffbs/gluon-parker/issues/3
> ffbs-mesh-vpn-parker: Let nodeconfig report success even if vpn disabled
